export var tz = 'userset';
export var w = '200';
export var id = '1';
export var nb = '10';
export var c1 = 'EUR/USD';
export var c2 = 'GBP/USD';
export var c3 = 'AUD/USD';
export var c4 = 'GBP/JPY';
export var c5 = 'USD/INR';
export var c6 = 'AUD/CAD';
export var c7 = 'EUR/GBP';
export var c8 = 'NZD/USD';
export var c9 = 'USD/CHF';
export var c10 = 'USD/CNY';
export var t = 'Forex Rates Live';
export var tc = '333333';
export var bdrc = 'e0e0e0';
export var mbg = 'ffffff';
export var fc = '333333';
  
export var ccHost = (("https:" == document.location.protocol) ? "https://www." : "http://www.");
  document.write(unescape("%3Cscript src='" + ccHost + "forexrates.net/widget/FR-FRW-1.php' type='text/javascript'%3E%3C/script%3E"));